version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - cd simple-app
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build

artifacts:
  base-directory: simple-app
  files:
    - '**/*'
